"""Write docs/options.md from the catalogue in dscim_cil.options.

Run before `zensical build`; the page is generated, not committed, so
it cannot drift from the catalogue. Standard library only.
"""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "src"))

from dscim_cil.options import CATALOGUE, REQUIRED

OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "docs" / "options.md"

HEADER = """\
<!-- Generated by scripts/generate_options_page.py from
     src/dscim_cil/options.py. Do not edit; edit the catalogue. -->

# Options reference

Every option dscim accepts, from the catalogue that `validate`, the
commands, and this page all read. Each option carries a status:

- **supported**: works through dscim-cil.
- **unsupported**: accepted by dscim but broken or restricted; the
  reason and source are given. `--allow-unsupported` lifts the
  validation block where noted.
- **dead**: accepted by dscim and ignored.
- **removed**: exists only on other dscim branches, not on main.

Restrictions are classed by origin: `library` (a dscim limitation),
`data` (a consequence of precomputed inputs), or `specification` (a
policy choice). The same records are available from the command line
through `dscim-cil options` and `dscim-cil explain OPTION`.
"""


def render_default(option) -> str:
    if option.default is REQUIRED:
        return "required"
    if option.config_required:
        return f"required in config (dscim's own default: {option.default!r})"
    return repr(option.default)


def render_option(option) -> list[str]:
    lines = [f"## `{option.name}`", "", option.summary, ""]
    status = option.status
    if option.restriction:
        status += f" ({option.restriction} restriction)"
    lines.append(f"- status: {status}")
    lines.append(f"- stages: {', '.join(option.stages) or 'none'}")
    lines.append(f"- modes: {', '.join(option.modes)}")
    lines.append(f"- default: `{render_default(option)}`")
    lines.append(f"- source: {option.citation}")
    if option.reason:
        lines.extend(["", option.reason])
    if option.values:
        label = "Known values" if option.open_set else "Accepted values"
        lines.extend(["", f"{label}:", ""])
        for value in option.values:
            entry = f"- `{value.value!r}`: {value.status}"
            if value.restriction:
                entry += f" ({value.restriction} restriction)"
            lines.append(entry)
            if value.reason:
                lines.append(f"    - {value.reason}")
            if value.citation:
                lines.append(f"    - source: {value.citation}")
        if option.open_set:
            lines.append("- other values are legal; these are the catalogued ones")
    lines.append("")
    return lines


def main() -> None:
    lines = [HEADER]
    for name in sorted(CATALOGUE):
        lines.extend(render_option(CATALOGUE[name]))
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
